const DEFAULTS={rate:10,maxAccuracy:35,minMove:3,maxSpeed:180};
const S={map:null,watch:null,active:false,paused:false,last:null,lastTs:0,points:[],distance:0,start:null,pauseStart:null,pausedMs:0,timer:null,marker:null,circle:null,gpsLine:null,roadLine:null,settings:{...DEFAULTS},origin:null,destination:null,planned:null,lastSummary:null,wake:null};
const $=id=>document.getElementById(id), money=n=>Number(n||0).toLocaleString('es-MX',{style:'currency',currency:'MXN',minimumFractionDigits:2});
const time=ms=>{let s=Math.floor(Math.max(0,ms)/1000),h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60),x=s%60;return [h,m,x].map(v=>String(v).padStart(2,'0')).join(':')};
function status(x){$('status').textContent=x}
function elapsed(){if(!S.start)return 0;return Date.now()-S.start-S.pausedMs-(S.paused&&S.pauseStart?Date.now()-S.pauseStart:0)}
function update(){ $('distanceVal').textContent=S.distance.toFixed(2)+' km';$('rateVal').textContent=money(S.settings.rate)+'/km';$('costVal').textContent=money(S.distance*S.settings.rate);$('timeVal').textContent=time(elapsed());$('pointsVal').textContent=S.points.length;$('routeDistance').textContent=S.planned==null?'—':S.planned.toFixed(2)+' km'}
function hav(a,b){const R=6371,r=x=>x*Math.PI/180,d1=r(b.lat-a.lat),d2=r(b.lon-a.lon),q=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(d2/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function init(){S.map=L.map('map').setView([19.0414,-98.2063],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(S.map);S.gpsLine=L.polyline([],{weight:6}).addTo(S.map);S.map.on('click',e=>{S.destination={lat:e.latlng.lat,lon:e.latlng.lng};$('destinationInput').value=`Punto del mapa (${e.latlng.lat.toFixed(5)}, ${e.latlng.lng.toFixed(5)})`;status('Destino seleccionado en el mapa');});try{S.settings={...DEFAULTS,...JSON.parse(localStorage.getItem('cv3_settings')||'{}')}}catch{};['rate','maxAccuracy','minMove','maxSpeed'].forEach(k=>$(k==='rate'?'rateInput':k==='maxAccuracy'?'accuracyInput':k==='minMove'?'minMoveInput':'maxSpeedInput').value=S.settings[k]);update()}
function visual(p){const ll=[p.lat,p.lon];if(!S.marker)S.marker=L.marker(ll).addTo(S.map);else S.marker.setLatLng(ll);if(!S.circle)S.circle=L.circle(ll,{radius:p.accuracy,weight:1}).addTo(S.map);else S.circle.setLatLng(ll).setRadius(p.accuracy)}
function position(pos){const c=pos.coords,p={lat:c.latitude,lon:c.longitude,accuracy:c.accuracy||999,ts:pos.timestamp||Date.now()};$('gpsVal').textContent='±'+Math.round(p.accuracy)+' m';$('accuracyBadge').textContent='GPS: ±'+Math.round(p.accuracy)+' m';if(p.accuracy>S.settings.maxAccuracy){status('Precisión insuficiente: ±'+Math.round(p.accuracy)+' m');return}visual(p);if(!S.last){S.last=p;S.lastTs=p.ts;S.points=[p];S.gpsLine.setLatLngs([[p.lat,p.lon]]);S.map.setView([p.lat,p.lon],17);update();return}const km=hav(S.last,p),m=km*1000,dt=Math.max(1,(p.ts-S.lastTs)/1000),speed=km/(dt/3600);if(m<S.settings.minMove)return;if(speed>S.settings.maxSpeed){status('Punto descartado por salto GPS');return}S.distance+=km;S.last=p;S.lastTs=p.ts;S.points.push(p);S.gpsLine.setLatLngs(S.points.map(x=>[x.lat,x.lon]));status('Viaje en curso');update()}
function startGPS(){if(!navigator.geolocation){status('Este dispositivo no permite geolocalización');return false}S.watch=navigator.geolocation.watchPosition(position,e=>status(({1:'Permiso GPS denegado',2:'Ubicación no disponible',3:'Tiempo de espera GPS'})[e.code]||'Error GPS'),{enableHighAccuracy:true,maximumAge:1000,timeout:15000});return true}
async function wake(){try{if('wakeLock'in navigator)S.wake=await navigator.wakeLock.request('screen')}catch{}}async function unwake(){try{await S.wake?.release()}catch{}S.wake=null}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&S.active&&!S.paused)wake()});
function start(){reset(false);S.active=true;S.start=Date.now();if(!startGPS()){S.active=false;return}S.timer=setInterval(update,1000);wake();$('startBtn').disabled=true;$('pauseBtn').disabled=false;$('finishBtn').disabled=false;status('GPS de alta precisión activado')}
function pause(){if(!S.active)return;if(!S.paused){S.paused=true;S.pauseStart=Date.now();if(S.watch!==null)navigator.geolocation.clearWatch(S.watch);S.watch=null;$('pauseBtn').textContent='Continuar';status('Viaje pausado')}else{S.paused=false;S.pausedMs+=Date.now()-S.pauseStart;S.pauseStart=null;startGPS();wake();$('pauseBtn').textContent='Pausar';status('Viaje en curso')}}
function reset(clear=true){if(S.watch!==null)navigator.geolocation.clearWatch(S.watch);clearInterval(S.timer);unwake();Object.assign(S,{watch:null,active:false,paused:false,last:null,lastTs:0,points:[],distance:0,start:null,pauseStart:null,pausedMs:0,timer:null,origin:null,destination:null,planned:null,lastSummary:null});if(clear){S.gpsLine.setLatLngs([]);if(S.roadLine){S.map.removeLayer(S.roadLine);S.roadLine=null}if(S.marker){S.map.removeLayer(S.marker);S.marker=null}if(S.circle){S.map.removeLayer(S.circle);S.circle=null}$('originInput').value='';$('destinationInput').value='';$('gpsVal').textContent='—';$('accuracyBadge').textContent='GPS: esperando'}update()}
function current(){return new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(p=>ok({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),()=>no(Error('No se pudo obtener GPS')),{enableHighAccuracy:true,maximumAge:0,timeout:15000}))}
async function geocode(q){const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=mx&q='+encodeURIComponent(q),{headers:{'Accept-Language':'es-MX'}});if(!r.ok)throw Error('No respondió el buscador de direcciones');const d=await r.json();if(!d[0])throw Error('Dirección no encontrada');return {lat:+d[0].lat,lon:+d[0].lon,name:d[0].display_name}}
async function route(){try{let a=S.origin;if(!a){status('Obteniendo origen GPS…');a=await current();S.origin=a;$('originInput').value='GPS ('+a.lat.toFixed(5)+', '+a.lon.toFixed(5)+')'}let b=S.destination;if(!b){const q=$('destinationInput').value.trim();if(!q)throw Error('Escribe un destino o selecciónalo en el mapa');status('Buscando destino…');b=await geocode(q);S.destination=b}$('destinationInput').value=b.name||$('destinationInput').value;status('Calculando ruta por calles…');const u=`https://router.project-osrm.org/route/v1/driving/${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson`;const r=await fetch(u);if(!r.ok)throw Error('Servidor de rutas no disponible');const d=await r.json();if(d.code!=='Ok')throw Error('No se encontró ruta');S.planned=d.routes[0].distance/1000;if(S.roadLine)S.map.removeLayer(S.roadLine);S.roadLine=L.geoJSON(d.routes[0].geometry,{style:{weight:5,dashArray:'10 8'}}).addTo(S.map);S.map.fitBounds(S.roadLine.getBounds(),{padding:[20,20]});status('Ruta por calles: '+S.planned.toFixed(2)+' km');update()}catch(e){status(e.message)}}
function save(x){let h=[];try{h=JSON.parse(localStorage.getItem('cv3_history')||'[]')}catch{};h.unshift(x);localStorage.setItem('cv3_history',JSON.stringify(h.slice(0,100)))}
function finish(){if(!S.active)return;if(S.watch!==null)navigator.geolocation.clearWatch(S.watch);clearInterval(S.timer);unwake();S.active=false;S.paused=false;const x={id:Date.now().toString(),date:new Date().toISOString(),origin:$('originInput').value||'GPS',destination:$('destinationInput').value||'No indicado',planned:S.planned,gps:S.distance,rate:S.settings.rate,cost:S.distance*S.settings.rate,time:elapsed(),points:S.points.length,track:S.points};S.lastSummary=x;save(x);showSummary(x);$('startBtn').disabled=false;$('pauseBtn').disabled=true;$('finishBtn').disabled=true;$('pauseBtn').textContent='Pausar';status('Viaje guardado');update()}
function summary(x){return `<div class="summary-grid"><div class="summary-box"><span>Distancia GPS</span><strong>${x.gps.toFixed(2)} km</strong></div><div class="summary-box"><span>Ruta por calles</span><strong>${x.planned==null?'—':x.planned.toFixed(2)+' km'}</strong></div><div class="summary-box"><span>Tiempo</span><strong>${time(x.time)}</strong></div><div class="summary-box"><span>Tarifa</span><strong>${money(x.rate)}/km</strong></div><div class="summary-box"><span>Puntos GPS</span><strong>${x.points}</strong></div><div class="summary-box"><span>Total</span><strong>${money(x.cost)}</strong></div></div>`}
function showSummary(x){$('summaryContent').innerHTML=summary(x);$('summaryDialog').showModal()}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function receipt(x){const w=open('','_blank');if(!w){alert('Permite ventanas emergentes para ver el recibo');return}w.document.write(`<html><head><title>Recibo Costo de Viaje</title><style>body{font-family:Arial;max-width:520px;margin:30px auto;padding:20px;color:#111}.r{display:flex;justify-content:space-between;margin:12px 0}.total{font-size:1.5em;font-weight:bold}hr{border:0;border-top:1px solid #ccc}.note{font-size:12px;color:#666}button{padding:10px 15px}@media print{button{display:none}}</style></head><body><h1 style="text-align:center">COSTO DE VIAJE</h1><p style="text-align:center">${new Date(x.date).toLocaleString('es-MX')}</p><hr><div class="r"><span>Origen</span><b>${esc(x.origin)}</b></div><div class="r"><span>Destino</span><b>${esc(x.destination)}</b></div><div class="r"><span>Distancia GPS</span><b>${x.gps.toFixed(2)} km</b></div><div class="r"><span>Ruta por calles</span><b>${x.planned==null?'—':x.planned.toFixed(2)+' km'}</b></div><div class="r"><span>Tiempo</span><b>${time(x.time)}</b></div><div class="r"><span>Tarifa</span><b>${money(x.rate)}/km</b></div><hr><div class="r total"><span>TOTAL</span><span>${money(x.cost)}</span></div><p class="note">La precisión GPS depende del dispositivo y las condiciones de recepción. Este recibo registra la información del viaje guardada localmente.</p><button onclick="print()">Imprimir / Guardar PDF</button></body></html>`);w.document.close()}
function history(){let h=[];try{h=JSON.parse(localStorage.getItem('cv3_history')||'[]')}catch{};if(!h.length){$('historyList').innerHTML='<p class="empty">No hay viajes guardados.</p>';return}$('historyList').innerHTML=h.map((x,i)=>`<div class="history-item"><b>${money(x.cost)}</b><small>${new Date(x.date).toLocaleString('es-MX')}</small><div class="history-row"><span>${x.gps.toFixed(2)} km · ${time(x.time)}</span><button class="secondary" data-i="${i}">Recibo</button></div></div>`).join('');document.querySelectorAll('#historyList button').forEach(b=>b.onclick=()=>receipt(h[+b.dataset.i]))}
function exportH(){const b=new Blob([localStorage.getItem('cv3_history')||'[]'],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='historial-costo-de-viaje.json';a.click();URL.revokeObjectURL(u)}
$('startBtn').onclick=start;$('pauseBtn').onclick=pause;$('finishBtn').onclick=finish;$('routeBtn').onclick=route;$('originGpsBtn').onclick=async()=>{try{const p=await current();S.origin=p;$('originInput').value='GPS ('+p.lat.toFixed(5)+', '+p.lon.toFixed(5)+')';S.map.setView([p.lat,p.lon],17);visual(p);status('Origen GPS ±'+Math.round(p.accuracy)+' m')}catch(e){status(e.message)}};$('destinationMapBtn').onclick=()=>status('Toca el mapa para elegir el destino');$('centerBtn').onclick=async()=>{try{const p=await current();visual(p);S.map.setView([p.lat,p.lon],17)}catch(e){status(e.message)}};$('settingsBtn').onclick=()=>$('settingsDialog').showModal();$('settingsForm').onsubmit=()=>{S.settings={rate:Math.max(0,+$('rateInput').value||10),maxAccuracy:Math.max(5,+$('accuracyInput').value||35),minMove:Math.max(0,+$('minMoveInput').value||3),maxSpeed:Math.max(20,+$('maxSpeedInput').value||180)};localStorage.setItem('cv3_settings',JSON.stringify(S.settings));update()};$('historyBtn').onclick=()=>{$('historyDialog').showModal();history()};$('closeHistory').onclick=()=>$('historyDialog').close();$('exportHistoryBtn').onclick=exportH;$('clearHistoryBtn').onclick=()=>{if(confirm('¿Borrar todo el historial?')){localStorage.removeItem('cv3_history');history()}};$('receiptBtn').onclick=()=>receipt(S.lastSummary);$('newTripBtn').onclick=()=>{$('summaryDialog').close();reset(true);status('Listo para iniciar')};$('clearRouteBtn').onclick=()=>{S.origin=null;S.destination=null;S.planned=null;$('originInput').value='';$('destinationInput').value='';if(S.roadLine){S.map.removeLayer(S.roadLine);S.roadLine=null}update()};init();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});
